### ISSUE TITLE
Like♥ in Gitalk is not available.

### ISSUE THREAD

**Issue by david990917** [sjtu-ieee/ieee.icu#167]
When I click Like♥ in Gitalk, there is no response.

Little Problem😀
Great Support to U!

**Comment by keithnull** [comment]
It might be a bug of Gitalk. I've noticed it earlier but has no way to fix it now.

But anyway, your like will take effect after refreshing that page.

**Comment by david990917** [comment]
Yes, just a few seconds, I refreshed the page, I find my like.

I love your pages, and I think it will give great help to our students. 👍

**Comment by keithnull** [comment]
I think this issue has been fixed by upstream Gitalk already: https://github.com/gitalk/gitalk/pull/416
