### ISSUE TITLE
CS157 程序设计思想与方法（荣誉）（C++） - IEEE.ICU

### ISSUE THREAD

**Issue by ieee-icu** [sjtu-ieee/ieee.icu#172]
https://ieee.icu/#/courses/grade-1/CS157 

 上海交通大学 IEEE 试点班，一个充满了「神仙」课程的专业，本网站旨在记录这些课程的信息以及历届学生对其的评价

**Comment by zengkaipeng** [comment]
老师上课就是照本宣科念ppt，祖传作业祖传ppt，尤其要注意上课前五分钟的老师随堂测试，有机会一定要拍下来，因为期末考题里面的坑大多出自此处，这些资料老师在考前并不会发给同学们
